In [4]:
import pandas as pd
from pathlib import Path

Path("../data/processed").mkdir(parents=True, exist_ok=True)

gbd = pd.read_csv("../data/raw/ihme_gbd_india_diabetes.csv")

gbd.head()
gbd.columns

Index(['population_group_id', 'population_group_name', 'measure_id',
       'measure_name', 'location_id', 'location_name', 'sex_id', 'sex_name',
       'age_id', 'age_name', 'cause_id', 'cause_name', 'metric_id',
       'metric_name', 'year', 'val', 'upper', 'lower'],
      dtype='str')

In [5]:
gbd_clean = gbd[
    (gbd["location_name"] == "India") &
    (gbd["sex_name"] == "Both") &
    (gbd["age_name"] == "Age-standardized") &
    (gbd["cause_name"].str.contains("Diabetes", case=False, na=False)) &
    (gbd["metric_name"] == "Rate")
].copy()

gbd_clean = gbd_clean[
    ["year", "measure_name", "val", "upper", "lower"]
]

gbd_clean.head()

   year measure_name        val      upper      lower
0  1990       Deaths  26.559467  37.872495  19.000808
1  1991       Deaths  26.680584  38.582210  19.107473
2  1992       Deaths  26.796212  38.754831  19.274543
3  1993       Deaths  26.534771  37.975803  19.668354
4  1994       Deaths  26.665199  37.806992  19.615062

In [6]:
diabetes_burden = gbd_clean.pivot_table(
    index="year",
    columns="measure_name",
    values="val"
).reset_index()

diabetes_burden.columns.name = None

diabetes_burden.head()

,year,DALYs (Disability-Adjusted Life Years),Deaths,Incidence,Prevalence,YLDs (Years Lived with Disability),YLLs (Years of Life Lost)
0,1990,949.405983,26.559467,202.431917,4429.816049,345.628099,603.777893
1,1991,960.769871,26.680584,202.889033,4428.289730,354.928093,605.841787
2,1992,971.164072,26.796212,203.663534,4458.347037,364.412942,606.751139
3,1993,973.649743,26.534771,204.702504,4503.289644,372.856341,600.793412
4,1994,980.484220,26.665199,205.952956,4546.535606,379.054940,601.429290

In [7]:
diabetes_burden.to_csv(
    "../data/processed/india_diabetes_burden_clean.csv",
    index=False
)