In [2]:
import pandas as pd
from pathlib import Path

Path("../data/processed").mkdir(parents=True, exist_ok=True)

In [3]:
vdem = pd.read_csv("../data/raw/vdem_liberal_democracy_index.csv")

vdem.head()

,Entity,Code,Year,Liberal democracy index,World region according to OWID
0,Afghanistan,AFG,1789,0.029,Asia
1,Afghanistan,AFG,1790,0.029,Asia
2,Afghanistan,AFG,1791,0.029,Asia
3,Afghanistan,AFG,1792,0.029,Asia
4,Afghanistan,AFG,1793,0.029,Asia

In [4]:
india_vdem = vdem[vdem["Entity"] == "India"].copy()

india_vdem.head()

,Entity,Code,Year,Liberal democracy index,World region according to OWID
13221,India,IND,1789,0.069,Asia
13222,India,IND,1790,0.069,Asia
13223,India,IND,1791,0.069,Asia
13224,India,IND,1792,0.069,Asia
13225,India,IND,1793,0.069,Asia

In [5]:
india_vdem = india_vdem[["Year", "Liberal democracy index"]].rename(
    columns={
        "Year": "year",
        "Liberal democracy index": "liberal_democracy_index"
    }
)

india_vdem.head()

       year  liberal_democracy_index
13221  1789                    0.069
13222  1790                    0.069
13223  1791                    0.069
13224  1792                    0.069
13225  1793                    0.069

In [6]:
india_vdem.to_csv(
    "../data/processed/india_vdem_freedom.csv",
    index=False
)